### ISSUE TITLE
The code-generation does not produce a binding.gyp file

### ISSUE THREAD

**Issue by swist** [NodeRT/NodeRT#10]
I'm new to windows development, but I assume that is not done because of the licensing restriction - so that the code cannot be published and rebuilt.

I do have a specific use-case however. I would like to build the winRT libraries for node-webkit, so that means swapping out node-headers for the node-webkit specific ones.

Normally I would pull a package from npm and just run nw-gyp on the source code. It would then pick up the contents on binding.gyp file and rebuild stuff using its own headers accordingly. 

The code generation step in nodeRT does not produce such a file and I am unable to rebuild the binaries using nw-gyp. On another hand if I point the nodeRT builder to the directory containing the headers from node-webkit, I get a cryptic error telling me to build the bindings manually. What should I do?

**Comment by nadavbar** [comment]
Assuming you are using the code in the master branch, it should generate a binding.gyp file for you.
Take a look that the directory after the generator gives you the error - it should be there.
Can you try and see if running nw-gyp from there works?

Also, we actually have all of the modules pushed to the npm, currently compatible with windows 8.1 and Visual Studio 2013 - take a look here: https://www.npmjs.com/search?q=NodeRT

So, for example, running "npm install windows.devices.geolocation" will install the for you the wrapper for the geolocation namespace, including the binding.gyp file.

**Comment by swist** [comment]
That seems to have worked, but I have run into other issues with node-webkit. Are there any plans to support node 0.11? Or could you perhaps point me in the direction of something that would help me understand how to recompile the extensions with the new version of NaN?

**Comment by nadavbar** [comment]
We plan to move to use NaN soon, and already started to do some work on this direction. (You can track the changes in NaN branch of NodeRT).

If it's possible, using node-webkit that is compatible with version 0.10.* should work out of the box.

**Comment by swist** [comment]
Great, thanks for the support! Seems like everything is sorted out for now, our team got it running with nw 0.8.6, will get back if we find anything unusual
