### ISSUE TITLE
Question: Using generated typescript definition files.

### ISSUE THREAD

**Issue by jeremywho** [NodeRT/NodeRT#130]
I can't figure out how to take advantage of the typescript definition file generated for a given module.

Installation works fine. 
I can use the module via `require` fine, but I can't get `import` to work.

Is there another step required to use the typescript definition?

**Comment by matijarmk** [comment]
@jeremywho did you manage to figure this out? Im trying to import nodeRT without any success. Typescript definition files are not being detected for some reason?
