### ISSUE TITLE
Electron to Require Native Modules in the Renderer Process to be NAPI or Context Aware

### ISSUE THREAD

**Issue by TheLastRar** [NodeRT/NodeRT#149]
See https://github.com/electron/electron/issues/18397

The modules created by NodeRT are currently none of these

Possibly related issue https://github.com/NodeRT/NodeRT/issues/70

**Comment by Draginfable** [comment]
app.allowRendererProcessReuse will be removed on electron 14, so this module will not work anymore.

**Comment by felixrieseberg** [comment]
That's not quite accurate, it'll still work - you'll have to require it in the `main` process though. I'm closing this issue in favor of https://github.com/NodeRT/NodeRT/issues/158.
