### ISSUE TITLE
Why i got "fatal error C1107: could not find assembly 'Windows.winmd' "?

### ISSUE THREAD

**Issue by cikpak** [NodeRT/NodeRT#152]
.winmd file is present in VS folder and in Windows SDK folde, but is named platform.winmd. If i'm trying to rename this file from platform.winmd to Windows.winmd i got a long error, something like parameters are already set from other file. How can i fix this and succesfuly install this package?

**Comment by Brouilles** [comment]
Same problem. Any solution @cikpak?
