### ISSUE TITLE
Support for Windows 11?

### ISSUE THREAD

**Issue by NyaomiDEV** [NodeRT/NodeRT#160]
As per the title. I do have Windows 11 SDKs, but I am still not understanding how this should work then.

**Comment by demosjarco** [comment]
Following [MaySoMusician's fork](MaySoMusician), I added vs2022 and windows 11 support. Can you test them out and let me know if there are any issues? Packages are available with `@nodert-win11` and `@nodert-win11-22h2` prefix.

**Comment by NyaomiDEV** [comment]
I don't have this use case anymore, sorry
