### ISSUE TITLE
Discussion: Why not just publish built modules to npm?

### ISSUE THREAD

**Issue by CharlieHess** [NodeRT/NodeRT#26]
Why not remove the burden of generating the template & building it and publish the modules to npm directly? Then we could just do:
```
npm install windows.foundation
```
``` js
require('windows.foundation');
```
like any other dependency. Platform targeting could be abstracted behind the npm scripts, and you could resolve versioning issues by publishing under different accounts.

**Comment by nadavbar** [comment]
Although I did upload older version of the the modules to the NPM several years ago, there are a few issues with it, like versioning, the code is static and we need to update it when the API changes, and in general it harder to maintain that amount of modules.

What I'm currently working on publishing the generation tool to npm with a node-gyp like usage options. 
I have a first version of the package working here: https://github.com/NodeRT/nodert-npm, and will be happy to hear any comments/suggestions.

**Comment by felixrieseberg** [comment]
+1 on publishing to npm - building another packaging tool for Node modules is generally a bad idea.

**Comment by paulcbetts** [comment]
It's really a far better idea to just publish these. You can use usernames as namespaces, something like, `@win10-10586/windows-foundation`. Write some tools to automate this so it isn't a pain to generate the packages

**Comment by nadavbar** [comment]
@paulcbetts are you referring to scopes? https://docs.npmjs.com/misc/scope
Can you install an npm package according to a specific user?

**Comment by paulcbetts** [comment]
@nadavbar Yep, scopes

**Comment by nadavbar** [comment]
Thanks, my only concern here is that when using scopes, the scope should be explicitly specified when requiring the module, e.g:
```javascript
var foundation = require('@win-10/windows.foundation')
```

I guess this makes sense, I'm just abit concerned regarding how many node devs are actually familiar with scopes and know how to use them.

**Comment by CharlieHess** [comment]
Certainly more node devs than will be willing to use a separate tool to generate the modules. 👍

**Comment by nadavbar** [comment]
Modules are now available on NPN under the @nodert-win10 and @nodert-win8.1 scopes
