### ISSUE TITLE
Error when setting the expirationTime of a Windows.UI.Notifications ToastNotification 

### ISSUE THREAD

**Issue by MarkTiedemann** [NodeRT/NodeRT#37]
[msdn://Windows.UI.Notifications.ToastNotification.expirationTime](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.notifications.toastnotification.expirationtime.aspx?cs-save-lang=1&cs-lang=csharp)

```js
toast.expirationTime = '05-Sep-16 21:08:07 +02:00'
```

`Error: Value to set is of unexpected type`

I guess the error is thrown because `expirationTime` is expected to be a `DateTimeOffset` instead of a `String`. 

Is there any way to fix this? Help would be much appreciated.

**Comment by nadavbar** [comment]
Try to first convert this to a Date object, e.g:
toast.expirationTime = new Date('05-Sep-16 21:08:07 +02:00');
Should do the trick.

**Comment by MarkTiedemann** [comment]
For some stupid reason I just didn't expect NodeRT to work with Javascript Dates. But it works perfectly. Thank you very much!
