### ISSUE TITLE
StorageFolder.createFileQueryWithOptions makes electron app crashed

### ISSUE THREAD

**Issue by rcasetta** [NodeRT/NodeRT#50]
Hello,

I'm trying to use NodeRT to use Windows search in My Pictures. Following the WinRT documentation, I wrote : 

```
var storage = require("windows.storage");
var search = require("windows.storage.search");

var picturesFolder = storage.KnownFolders.picturesLibrary;

var fileTypeFilter = [".jpg"];
var queryOptions = new search.QueryOptions(search.CommonFileQuery.orderByDate, fileTypeFilter);

var results = picturesFolder.createFileQueryWithOptions(queryOptions);
```

Everything works fine till I add the last line, which make the app crashed. When I launch VS debugger, it prints : 
```
Unhandled exception at 0x00000001400E91DE in app.exe. 0xC0000005: Access violation writing location 0x0000000000000000.  

If there is an handler for this exception, the program may be safely continued.
```
Do you have an idea about this issue? 

Thanks !

**Comment by nadavbar** [comment]
Thanks for reporting this issue, I'm able to reproduce it also for node.js v.6.6. will take take a look and get back with a fix.

**Comment by nadavbar** [comment]
Hi @rcasetta, as a temporary workaround, the following change should fix you issue (verified on node.js):
In your code, switch the order of requires such that
```
require("windows.storage.search")
```
Will come before
```
require("windows.storage")
```

I'm working on a fix for the issue but this should get you going in the meantime.

**Comment by rcasetta** [comment]
@nadavbar Thanks for your reply, your fix works : I can now make a query, the app doesn't crash.
But now, when I do: 
```
query.getFilesAsync(function (err, files) {
  console.log(files.length); // -> shows 514
  for (var i = 0 ; i < files.length ; i++) {
    console.log(files[i]);
  }
});
```
the app crashes...

If i write the exact same code with `picturesFolder` instead of a query, there is no problem.

Any idea on that issue ? 

Thanks for the help :)

**Comment by nadavbar** [comment]
Hi @rcasetta , this seems like a byproduct of the same issue that causes cross module dependencies issues. Until we fix the issue - the following workaround should fix the issue for you locally:
Make sure that the windows.storage and windows.storage.search module folders are under the same node_modules dir (without the @nodert-win10 folder to separate them).
Basically, the setting that I got working with the script above is:
 --- my_script.js
 ---node_modules
|--------windows.storage
|--------windows.storage.search

Note that after doing this change you need to explicitly require 'windows.storage' and 'windows.storage.search' without the @nodert-win10 prefix (in case you were using it.

Let me know if the issue persists.

I'll hopefully get to fixing the deeper dependency issue soon.
Thanks!
Nadav

**Comment by rcasetta** [comment]
Hello @nadavbar, your fix works perfectly ! 

Thanks for the help and your quick answers ! 
Richard
