### ISSUE TITLE
Test building with windows-build-tools

### ISSUE THREAD

**Issue by nadavbar** [NodeRT/NodeRT#54]
We should verify that the build-tools compiler support c++/cx and build it with:
https://github.com/felixrieseberg/windows-build-tools

Hopefully this could help us remove the VS2015 dependency.

**Comment by dantler** [comment]
👍  This would be great!

**Comment by dantler** [comment]
I tested this out on a new machine and it seems to work.  Used NodeRt version 0.2.95 on node 6.10.3, Windows 10 x64 15063.  ✔️

**Comment by nadavbar** [comment]
Awesome, thanks for verifying this!
