### ISSUE TITLE
"Failed to build the generated project, please try to build the project manually"

### ISSUE THREAD

**Issue by MarkTiedemann** [NodeRT/NodeRT#57]
The following command ...
```
NodeRTCmd.exe --namespace Windows.Devices.WiFi --winmd "C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd" --outdir "C:\dev\secret\location\prebuilt"
```
... fails with the following output:
```
Generating code for: Windows.Devices.WiFi...
Building Windows.Devices.WiFi...
Failed to build the generated project, please try to build the project manually
Generated project files are located at: C:\dev\secret\location\prebuilt\windows.devices.wifi
```

The system I'm using has:

- `ver`: Microsoft Windows [Version 10.0.14393]
- `node -v`: v7.5.0
- `node-gyp -v`: v3.5.0
- `echo %GYP_MSVS_VERSION%`: 2015

I also ran `npm i -g windows-build-tools` for good measure.

It would be really helpful to have a more detailed error message in this case. :)

EDIT: Turns out my python path was set incorrectly. 

Still it would be great if there was a build error log or a more detailed error message so it's easier to figure out what went wrong.

PS: Awesome project!

**Comment by nadavbar** [comment]
Happy to see you got it working, will look into adding a more verbose log to the cmd line tool. In the meanwhile and for the future - another option would be to cd into the directory of the generated module and running
```
node-gyp rebuild --msvs_version=2015
```

This will give you a more verbose message.

**Comment by MarkTiedemann** [comment]
Yep, that's exactly what I did. :) And when I did it, `node-gyp` outputted the detailed error message about the python path causing issues. 

I'm just asking to skip that step. :) So this really isn't an important issue at all, it's more about laziness. ;)

**Comment by nadavbar** [comment]
@MarkTiedemann  - It's pretty funny but I actually added that feature a while ago but forgot to update the documentation about it.
Next time you run NodeRTCmd, you can specify the --verbose feature and it should give you the build process output.
Gonna update the README now..

**Comment by MarkTiedemann** [comment]
That's awesome, thanks a lot!
