### ISSUE TITLE
Issue with npm install @nodert-win10/windows.data.xml.dom

### ISSUE THREAD

**Issue by GeetaKrishnaAdhikari** [NodeRT/NodeRT#76]
Could not install and work with electron-windows-notifications. Since this module depends on @nodert-win10/windows.data.xml.dom, I installed Visual Studio 2015 and also installed c++ tools too. I have no knowledge about Visual Studio.
Error is:
 CollectionsConverterUtils.cpp
..\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winm
d': please specify the assembly search path using /AI or by setting the LIBPA
TH environment variable [C:\Users\Krishna\Desktop\New folder (3)\node_modules
\@nodert-win10\windows.data.xml.dom\build\binding.vcxproj]
..\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.wi
nmd': please specify the assembly search path using /AI or by setting the LIB
PATH environment variable [C:\Users\Krishna\Desktop\New folder (3)\node_modul
es\@nodert-win10\windows.data.xml.dom\build\binding.vcxproj]
..\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly
 'Windows.winmd': please specify the assembly search path using /AI or by set
ting the LIBPATH environment variable [C:\Users\Krishna\Desktop\New folder (3
)\node_modules\@nodert-win10\windows.data.xml.dom\build\binding.vcxproj]
..\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Window
s.winmd': please specify the assembly search path using /AI or by setting the
 LIBPATH environment variable [C:\Users\Krishna\Desktop\New folder (3)\node_m
odules\@nodert-win10\windows.data.xml.dom\build\binding.vcxproj]
  win_delay_load_hook.cc
C:\Users\Krishna\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\s
rc\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windo
ws.winmd': please specify the assembly search path using /AI or by setting th
e LIBPATH environment variable [C:\Users\Krishna\Desktop\New folder (3)\node_
modules\@nodert-win10\windows.data.xml.dom\build\binding.vcxproj].
Thank you in BeforeHand.

**Comment by nadavbar** [comment]
Can you make sure that you have the windows 10 SDK installed? Please refer to the README of this repo for all of the required prerequisites of NodeRT.

**Comment by ErraticFox** [comment]
I've also have the same error. I've checked all the dependencies, installed them and rebooted my computer. 

I don't have `windows.winmd` inside `C:\Program Files (x86)\Windows Kits\10\UnionMetadata` though there's one inside `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.15063.0` would this be throwing the error?

For VS Express (now VS Community) could you specify what to install with it? As it now asks you what modules to install. I currently have the ones in the picture installed.
![2017-07-23_07h09_59](https://user-images.githubusercontent.com/6486865/28498924-9e105e3c-6f77-11e7-8375-8aab3f09d465.png)


The command I use is `npm i @nodert-win10/windows.media` and my response is: 
```
C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.media>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "" rebuild --msvs_version=2015 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
  win_delay_load_hook.cc
..\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LI
BPATH environment variable [C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.media\build\binding.vcxproj]
..\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH enviro
nment variable [C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.media\build\binding.vcxproj]
..\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH en
vironment variable [C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.media\build\binding.vcxproj]
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windows.winmd': please specif
y the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.medi
a\build\binding.vcxproj]
..\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environm
ent variable [C:\Users\errat\Documents\GitHub\soundobs\node_modules\@nodert-win10\windows.media\build\binding.vcxproj]
```

Thanks.

**Comment by GeetaKrishnaAdhikari** [comment]
Thank you Nadavbar for the response. It's a mistake on my part. We need to add cl.exe to the system variable(path). Erratic fox could you try setting this to your system variable(path) and try if it works. C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin 
All the Best

**Comment by ErraticFox** [comment]
I was misunderstood and installed VS Express 2017 not 2015. That fixed my problem. You can close the issue, thanks.
