### ISSUE TITLE
@nodert-win10/windows.ui.notifications web based images in toast not working

### ISSUE THREAD

**Issue by olegshilov** [NodeRT/NodeRT#99]
Hi.
I am trying to show an image from the web but it isn't working.
In following code works only local image.
```
const { XmlDocument } = require('@nodert-win10/windows.data.xml.dom');
const {
  ToastNotification,
  ToastNotificationManager
} = require('@nodert-win10/windows.ui.notifications');
const path = require('path');

const localImage = path.join(__dirname, 'image.jpg');
const webImage = 'http://picsum.photos/360/202?image=11';
const template = `
  <toast launch="app-defined-string">
    <visual>
      <binding template="ToastGeneric">
        <image id="1" placement="appLogoOverride" hint-crop="circle" src="${localImage}"/>
        <image id="2" placement="hero" src="${webImage}"/>
      </binding>
    </visual>
  </toast>
`;

const xml = new XmlDocument();
xml.loadXml(template);

const toast = new ToastNotification(xml);
const notifier = ToastNotificationManager.createToastNotifier(appId);

notifier.show(toast);
```

**Comment by 23phy** [comment]
I'm interested on how you managed to successfully compile the `windows.ui.notifications` module. 🤔 I tried with no success. Please, if you have time maybe you can tell me the steps you took, and the environment.

**Comment by felixrieseberg** [comment]
This is not an issue with NodeRT - desktop apps outside of the UWP desktop bridge don’t get to use anything but local images in notifications. That’s a limitation of Windows. Sorry!

**Comment by gauravms** [comment]
@felixrieseberg is there a documentation link on microsoft for this limitation?
Also wanted to ask, if instead of using NodeRT, I created an exe (like node-notifier does) using my electron app id and then showed notification, will it work?

**Comment by gauravms** [comment]
@23phy I am wondering what other limitations might exist when using NodeRT. We are building an enterprise level Electron app that requires us to do almost anything that windows UWP Notification APIs provide.
So, I am thinking creating another application exe (intermediary app) that will register itself in startmenu and shortcut with it's own AppUserModelID and we use that application to show notifications on behalf of our Electron app. To enable interactions, our intermediary native app can launch the Electron app by using our Electron app's protocol link and pass it parameters via arguments. I think this design can work. Do you guys know of any possible dependencies/limitations that we might encounter in this design?
